V4.0.1-st (STABLE RELEASE)
GilbertGobbels/GAwesomeBot pull request #167
Opened 2017-06-02 07:51 UTC by GilbertGobbels

Dear reviewers and contributors, please clone this branch (release-4.0.1) locally, and follow the self-hosting guide on this repo's wiki to set it up. MAKE SURE EVERYTHING WORKS.

**This will be your last chance to fix bugs before we push to stable!**

Config.json will be updated to match the correct branch. No other changes will be pushed apart from bug fixes.

2017-06-02 09:36 UTC, KingDGrizzle commented
I'll clone this locally, and review accordingly

2017-06-02 10:29 UTC, KingDGrizzle commented
Hey @HilbertGilbertson wanna fix lottery?

2017-06-02 11:09 UTC, vladfrangu requested changes
Oh, maybe i should actually init this? serverData.name in maintainer page?

2017-06-02 11:18 UTC, GilbertGobbels commented on Web/views/pages/maintainer-version.ejs
> +	<title><%= serverData.name %> Maintainer Console</title>
Returns the bot name, AFAIK

2017-06-02 16:31 UTC, vladfrangu submitted a review, later dismissed

2017-06-27 11:27 UTC, vladfrangu approved these changes
Unless you are going to do any more changes, which won't be very hard to issue an update from the maintainer panel, I give my approval. Finishing touches should be implemented, and merged. Have fun GAB users!

2017-07-10 12:17 UTC, merged