:sparkles: Unban command
GilbertGobbels/GAwesomeBot pull request #409
Opened 2018-12-16 20:43 UTC by GilbertGobbels

**Please describe the changes this PR makes and why it should be merged:**

**What does this PR do:**
- [ ] This PR changes internal functions, modules and/or utilities
  - [ ] This PR modifies the Extension API
- [x] This PR modifies commands
  - [ ] This PR changes command functions
  - [ ] This PR changes metadata for the command, updated in `commands.js`
  - [x] This PR removes and/or adds commands
- [ ] This PR modifies Web processing and/or content
  - [ ] This PR modifies static/ejs content
  - [ ] This PR modifies request processing (endpoint functions)
  - [ ] This PR modifies paths to existing resources
- [ ] This PR **only** includes non-code changes, like changes to default configurations, README, typos, etc.

2018-12-16 21:25 UTC, vladfrangu requested changes

2018-12-16 21:25 UTC, vladfrangu commented on Commands/Public/unban.js
> +	return user.id === query || user.tag === query || user.username === query;
toLowerCase pls

2018-12-16 21:25 UTC, vladfrangu commented on Commands/Public/unban.js
> +		if (msg.suffix.includes("|")) [query, reason] = ArgParser.parseQuoteArgs(msg.suffix, "|");
`let [query, ...reason] = ArgParser.parseQuoteArgs(msg.suffix, msg.suffix.includes('|') ? '|' : '')`

2018-12-16 21:25 UTC, vladfrangu commented on Commands/Public/unban.js
> +		if (!msg.guild.me.permissions.has("BAN_MEMBERS")) {
Do this check before fetching

2018-12-17 21:36 UTC, GilbertGobbels commented
Approve or request more pls

2018-12-17 22:11 UTC, vladfrangu requested changes

2018-12-17 22:11 UTC, vladfrangu commented on Commands/Public/unban.js
> +		msg.sendInvalidUsage(commandData, "Huh? Unban what?");
```suggestion
 		msg.sendInvalidUsage(commandData, "Huh? Unban who?");
```

2018-12-17 22:14 UTC, merged